name: Deploy plugin to WordPress.org

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    name: Deploy updates
    runs-on: ubuntu-latest
    environment: wp.org plugin

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Build minified JavaScript and CSS and commit it just for the release
        run: |
          npm ci
          npm run build

      - name: WordPress.org plugin update
        uses: 10up/action-wordpress-plugin-deploy@fix/136
        with:
          generate-zip: true
          dry-run: true
        env:
          SVN_USERNAME: test
          SVN_PASSWORD: password
          VERSION: 0.0.1
          SLUG: glotpress
